### ISSUE TITLE
Why does fetching threads fail on services other than ESS?

### ISSUE THREAD

**Issue by spmcbride1201** [DecipherNow/gm-fabric-dashboard#113]
![image](https://user-images.githubusercontent.com/8700322/28273136-7dbc4e0c-6adb-11e7-8ddc-557e2437bc9f.png)

Error from Dev Tools
```
Fetching Threads failed TypeError: Cannot read property 'threads' of null
    at Object.fetchThreadsSuccess (https://private.deciphernow.com/services/apps/1.0/gmadmin/static/js/main.13e263b3.js:1:846905)
    at c (https://private.deciphernow.com/services/apps/1.0/gmadmin/static/js/main.13e263b3.js:1:1061149)
    at https://private.deciphernow.com/services/apps/1.0/gmadmin/static/js/main.13e263b3.js:1:1634937
    at f (https://private.deciphernow.com/services/apps/1.0/gmadmin/static/js/main.13e263b3.js:1:802991)
    at https://private.deciphernow.com/services/apps/1.0/gmadmin/static/js/main.13e263b3.js:1:1523218
    at https://private.deciphernow.com/services/apps/1.0/gmadmin/static/js/main.13e263b3.js:1:283910
    at dispatch (https://private.deciphernow.com/services/apps/1.0/gmadmin/static/js/main.13e263b3.js:1:1632507)
    at t.dispatch (https://private.deciphernow.com/services/apps/1.0/gmadmin/static/js/main.13e263b3.js:1:284395)
    at l (https://private.deciphernow.com/services/apps/1.0/gmadmin/static/js/main.13e263b3.js:1:1061553)
    at Object.u.(anonymous function) [as fetchThreadsSuccess] (https://private.deciphernow.com/services/apps/1.0/gmadmin/static/js/main.13e263b3.js:1:353819)
    at https://private.deciphernow.com/services/apps/1.0/gmadmin/static/js/main.13e263b3.js:1:848697
    at <anonymous>
```

**Comment by spmcbride1201** [comment]
We need to determine if the /threads endpoint exists for the services failing in this way (seem to be all but ESS) and determine if this might be due to ElasticSearch klobbering the request with a redirect to GMData

**Comment by spmcbride1201** [comment]
@tilleryd - Perhaps you might be able to look into this. This may intersect with the versioning stuff I mentioned about Finagle.

**Comment by spmcbride1201** [comment]
Some of the enhanced error handling in the AJAX Worker thread should help diagnose this issue. This needs likely needs attention from @joshua-rutherford if this is critical.

**Comment by spmcbride1201** [comment]
Upon further investigation, this is indeed due to different Finagle versions. Closing issue.
